parameters:
  publishAssemblies: false
  buildConfiguration: ''
  dependsOn: ''
  prepareAssemblyVersion: false

jobs:
  - job: BuildDrawingLibraries
    dependsOn: ${{ parameters.dependsOn }}
    steps:
    - ${{ if eq(parameters.prepareAssemblyVersion, true) }}:
      - download: current
        artifact: 'AssemblyVersionInfo'
    - powershell: |
        $assemblyVersionFilePath = "$(Pipeline.Workspace)\AssemblyVersionInfo\AssemblyVersion.txt"
        if (Test-Path $assemblyVersionFilePath) {
          $AssemblyVersion = Get-Content $assemblyVersionFilePath
          if (![string]::IsNullOrEmpty($AssemblyVersion)) {
            Write-Host "Using AssemblyVersion from previous job: $AssemblyVersion"
            Write-Host "##vso[task.setvariable variable=finalAssemblyVersion]$AssemblyVersion"
          } else {
            Write-Host "AssemblyVersion is empty, using default: 1.0.0.0"
            Write-Host "##vso[task.setvariable variable=finalAssemblyVersion]1.0.0.0"
          }
        } else {
          Write-Host "AssemblyVersion.txt not found, using default: 1.0.0.0"
          Write-Host "##vso[task.setvariable variable=finalAssemblyVersion]1.0.0.0"
        }
      displayName: 'Use or Set Assembly Version'
    # Checkout Repo
    - checkout: self
      displayName: Checkout IronSoftware.Drawing repository
      lfs: true
    - task: UseDotNet@2
      displayName: 'Install .Netcoreapp3.1 Core sdk'
      inputs:
        packageType: 'sdk'
        version: '3.x'
    - task: UseDotNet@2
      displayName: 'Install .NET5 sdk'
      inputs:
        packageType: 'sdk'
        version: '5.x'
    - task: UseDotNet@2
      displayName: 'Install .NET6 sdk'
      inputs:
        packageType: 'sdk'
        version: '6.x'
    - task: UseDotNet@2
      displayName: 'Install .NET7 sdk'
      inputs:
        packageType: 'sdk'
        version: '7.x'
    - task: UseDotNet@2
      displayName: 'Install .NET7 sdk'
      inputs:
        packageType: 'sdk'
        version: '8.x'
    # Build
    - task: DotNetCoreCLI@2
      displayName: Restore Solution NuGet Packages
      enabled: true
      continueOnError: true
      inputs:
        command: 'restore'
        projects: '$(Build.SourcesDirectory)/IronSoftware.Drawing/IronSoftware.Drawing.sln'
        verbosityRestore: Minimal
        feedsToUse: 'config'
        nugetConfigPath: '$(Build.SourcesDirectory)/IronSoftware.Drawing/nuget.config'
    - task: DotNetCoreCLI@2
      displayName: Build Drawing Libraries Solution
      inputs:
        command: 'build'
        projects: '$(Build.SourcesDirectory)/IronSoftware.Drawing/IronSoftware.Drawing.sln'
        arguments: >-
          --configuration
          ${{ parameters.buildConfiguration }}
          --no-restore
          --verbosity normal
          --property:AssemblyVersion=$(finalAssemblyVersion)
        versioningScheme: byEnvVar
        versionEnvVar: AssemblyVersion
    # Publish Pipeline Artifacts
    - task: CopyFiles@2
      displayName: 'Copy tests.runsettings file'
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)/IronSoftware.Drawing/IronSoftware.Drawing.Common.Tests'
        Contents: 'tests*.runsettings'
        TargetFolder: '$(Build.SourcesDirectory)/IronSoftware.Drawing/IronSoftware.Drawing.Common.Tests/bin/${{ parameters.buildConfiguration }}'
    - task: PublishPipelineArtifact@1
      displayName: Publish IronDrawing Test Data
      inputs:
        targetPath: '$(Build.SourcesDirectory)/IronSoftware.Drawing/IronSoftware.Drawing.Common.Tests/Data'
        artifact: 'IronDrawingDataTests'
        publishLocation: 'pipeline'
    - task: PublishPipelineArtifact@1
      displayName: Publish IronDrawing Test Assemblies
      inputs:
        targetPath: '$(Build.SourcesDirectory)/IronSoftware.Drawing/IronSoftware.Drawing.Common.Tests/bin/${{ parameters.buildConfiguration }}'
        artifact: 'IronDrawingTests'
        publishLocation: 'pipeline'
    - ${{ if eq(parameters.publishAssemblies, true) }}:
      - task: CopyFiles@2
        displayName: 'Copy LICENSE.txt file'
        inputs:
          SourceFolder: '$(Build.SourcesDirectory)'
          Contents: 'LICENSE.txt'
          TargetFolder: '$(Build.SourcesDirectory)/NuGet'
      - task: PublishPipelineArtifact@1
        displayName: Publish IronDrawing Assemblies
        inputs:
          targetPath: '$(Build.SourcesDirectory)/IronSoftware.Drawing/IronSoftware.Drawing.Common/bin/${{ parameters.buildConfiguration }}'
          artifact: 'IronDrawingAssemblies'
          publishLocation: 'pipeline'
      - task: PublishPipelineArtifact@1
        displayName: Publish IronDrawing NuGet Files
        inputs:
          targetPath: 'NuGet'
          artifact: 'IronDrawingNuGet'
          publishLocation: 'pipeline'