trigger:
  branches:
    include:
    - main
    - master
  paths:
    exclude:
    - NuGet
pr:
  branches:
    include:
    - master
    - main
    - develop
  paths:
    exclude:
    - NuGet

parameters:
  - name: testWindows
    displayName: Test Windows
    type: boolean
    default: True
  - name: testLinux
    displayName: Test Linux
    type: boolean
    default: True
  - name: testMacOS
    displayName: Test macOS
    type: boolean
    default: True

pool:
  vmImage: 'windows-latest'

variables:
  - group: IronDrawingVersions
  - name: buildConfiguration
    value: 'Debug'
  - name: AssemblyVersion
    value: $(IronDrawingMajorVersion).$(IronDrawingMinorVersion).$(IronDrawingRevisionVersion).$(Build.BuildID)

##### STEPS #####
stages:
## Restore & Build IronDrawing and Publish Artifact
- stage: BuildDrawingLibraries
  displayName: Build IronSoftware.Drawing Libraries
  dependsOn: []
  jobs:
    - template: job_templates/build_drawing_libraries.yml
      parameters:
        publishAssemblies: false
        buildConfiguration: $(buildConfiguration)
## Execute Windows Unit Tests
- template: stage_templates/run_tests_on_pool.yml
  parameters:
    OSPlatform: 'Windows'
    pool:
      vmImage: 'windows-latest'
    runUnitTests: ${{ parameters.testWindows }}
## Execute Linux Unit Tests
- template: stage_templates/run_tests_on_pool.yml
  parameters:
    OSPlatform: 'Ubuntu'
    pool:
      vmImage: 'ubuntu-latest'
    runUnitTests: ${{ parameters.testLinux }}
## Execute macOS Unit Tests
- template: stage_templates/run_tests_on_pool.yml
  parameters:
    OSPlatform: 'MacOs'
    pool:
      vmImage: 'macOS-latest'
    runUnitTests: ${{ parameters.testMacOS }}
